name: CI

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest
    # see /dev.Dockerfile
    container: warchantua/py-toml-dev:v1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: install toml-test
        run: |
            go install github.com/toml-lang/toml-test/cmd/toml-test@v1.4.0

      - name: Run python tests
        run: |
            pip -q install "tox>=4"
            tox run-parallel --parallel-no-spinner

      # TODO(warchant): many tests fail
      # - name: Run go tests
      #   run: |
      #       export PYTHONPATH=.
      #       e=0
      #       toml-test          ./tests/decoding_test.py || e=1
      #       toml-test -encoder ./tests/encoding_test.py || e=1
      #       exit $e
